#!/usr/bin/env node
/**
 * Bootstrap Environment Configuration
 * 
 * This script solves the chicken-and-egg problem of restoring .env from Supabase
 * when you don't have the initial Supabase credentials yet.
 * 
 * It reads the credentials from .memory/environment/production-config.md
 * and creates a minimal .env file with just the Supabase credentials,
 * then uses env:restore to pull down the complete configuration.
 * 
 * Usage:
 *   npm run env:bootstrap    # Bootstrap from memory
 *   npm run env:restore      # After bootstrap, restore full config
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

const PROJECT_ROOT = process.cwd();
const PRODUCTION_CONFIG_PATH = join(PROJECT_ROOT, '.memory/environment/production-config.md');
const ENV_PATH = join(PROJECT_ROOT, '.env');

function extractSupabaseCredentials(): {
  url: string;
  anonKey: string;
  serviceKey: string;
  encryptionKey: string;
} | null {
  console.log('📖 Reading production config from memory...');
  
  if (!existsSync(PRODUCTION_CONFIG_PATH)) {
    console.error('❌ Production config not found at:', PRODUCTION_CONFIG_PATH);
    console.error('   Expected file: .memory/environment/production-config.md');
    return null;
  }

  const configContent = readFileSync(PRODUCTION_CONFIG_PATH, 'utf-8');

  // Extract credentials using regex
  const urlMatch = configContent.match(/SUPABASE_URL=(.+)/);
  const anonKeyMatch = configContent.match(/SUPABASE_ANON_KEY=(.+)/);
  const serviceKeyMatch = configContent.match(/SUPABASE_SERVICE_KEY=(.+)/);
  const encryptionKeyMatch = configContent.match(/SECRETS_ENCRYPTION_KEY=(.+)/);

  if (!urlMatch || !anonKeyMatch || !serviceKeyMatch) {
    console.error('❌ Could not extract all required Supabase credentials from production config');
    return null;
  }

  return {
    url: urlMatch[1].trim(),
    anonKey: anonKeyMatch[1].trim(),
    serviceKey: serviceKeyMatch[1].trim(),
    encryptionKey: encryptionKeyMatch ? encryptionKeyMatch[1].trim() : '',
  };
}

function createBootstrapEnv(credentials: ReturnType<typeof extractSupabaseCredentials>) {
  if (!credentials) {
    throw new Error('No credentials provided');
  }

  console.log('✅ Supabase credentials extracted successfully');
  console.log(`   URL: ${credentials.url}`);
  console.log(`   Anon Key: ${credentials.anonKey.substring(0, 20)}...`);
  console.log(`   Service Key: ${credentials.serviceKey.substring(0, 20)}...`);
  
  if (credentials.encryptionKey) {
    console.log(`   Encryption Key: ${credentials.encryptionKey.substring(0, 16)}...`);
  }

  // Check if .env already exists
  if (existsSync(ENV_PATH)) {
    const backupPath = `${ENV_PATH}.backup.${Date.now()}`;
    const existingEnv = readFileSync(ENV_PATH, 'utf-8');
    writeFileSync(backupPath, existingEnv);
    console.log(`\n💾 Backed up existing .env to: ${backupPath}`);
  }

  // Create minimal .env with just Supabase credentials
  const envContent = `# ═══════════════════════════════════════════════════════════════
# TheWarden - Bootstrap Environment Configuration
# ═══════════════════════════════════════════════════════════════
# This file was auto-generated by npm run env:bootstrap
# Run "npm run env:restore" to load the complete configuration from Supabase
# Generated: ${new Date().toISOString()}
# ═══════════════════════════════════════════════════════════════

# Supabase Configuration (Required for env:restore)
SUPABASE_URL=${credentials.url}
SUPABASE_ANON_KEY=${credentials.anonKey}
SUPABASE_SERVICE_KEY=${credentials.serviceKey}
${credentials.encryptionKey ? `SECRETS_ENCRYPTION_KEY=${credentials.encryptionKey}` : ''}

# ═══════════════════════════════════════════════════════════════
# 📝 NEXT STEPS
# ═══════════════════════════════════════════════════════════════
# Run the following command to restore the complete .env file:
#   npm run env:restore
# ═══════════════════════════════════════════════════════════════
`;

  writeFileSync(ENV_PATH, envContent);
  console.log(`\n✅ Bootstrap .env created at: ${ENV_PATH}`);
  console.log('\n📋 Next steps:');
  console.log('   1. Run: npm run env:restore');
  console.log('   2. This will download the complete configuration from Supabase');
  console.log('   3. Your .env will be fully populated with all credentials');
}

async function main() {
  console.log('\n' + '='.repeat(60));
  console.log('🔐 TheWarden - Environment Bootstrap');
  console.log('='.repeat(60) + '\n');

  const credentials = extractSupabaseCredentials();
  if (!credentials) {
    console.error('\n❌ Bootstrap failed. Could not extract credentials.');
    process.exit(1);
  }

  createBootstrapEnv(credentials);

  console.log('\n✨ Bootstrap complete!');
  console.log('='.repeat(60) + '\n');
}

main().catch(error => {
  console.error('❌ Bootstrap error:', error);
  process.exit(1);
});
